### PR TITLE
Modified setup for oil

### PR DESCRIPTION
**Pull request by daubaris**
Paths needed some correction and also the formatter did it's job.

### CODE REVIEW

**Comment by andychu** [comment]
I would prefer not to have the reformatting.  It's hard for me to read the diff and see what actually changed.

We're probably won't merge anything back to py-yajl since it's archived, but I like to make minimal diffs to third party code to make looking through history easier.

**Comment by daubaris** [comment]
Yeah, sorry. Left only the important parts.

**Comment by andychu** [comment]
Hm I think this can be done from a shell script without changing `py-yajl` (although the shebang change is good)

I think you can just `cd` into that dir, and then build, and then symlink the resulting `.so` file into a certain place.

For example `build/dev.sh pylibc` builds the extension and runs tests.  

We should have `build/dev.sh yajl` that builds and runs their existing Python tests.  It doesn't have to  use the `py-ext` function, which assumes a certain layout that `yajl` doesn't follow.

I think we can rewrite/adapt their `run_tests.sh`  script because I couldn't get that to work.

**Comment by andychu** [comment]
Also the reason I'm being a bit picky is because the "dev build" is the simple part.  The harder part is statically linking yajl into the Oil "app bundle".  I'm not sure exactly how that will play out.

I described that a couple years ago in [Rewriting Python's Build System From Scratch](http://www.oilshell.org/blog/2017/05/05.html)

Either way, being able to `import yajl` in Oil is something to test.  Does that work with this change?
It's pretty similar to running unit tests, which also do `import yajl`.

**Comment by daubaris** [comment]
I've tried to create a mock test file, and copy few of the unit tests from `py-yajl` module. It surprisingly passed. So I could create an almost identical file to `py-yajl` tests in `oil` and remove the `python 3` stuff to check further.

**Comment by andychu** [comment]
OK let me give this a stab... I think I have an idea of how it should look.  I want to get yajl integrated with the Oil dev build with minimal changes to it.  Maybe write a `json echo` demo.

And then do the statically linked "app bundle" build, which is harder.

But the API and testing are still up for discussion / contribution.

**Pull request closed without merging**
